### ISSUE TITLE
additions/removals not highlighted with magit-delta

### ISSUE THREAD

**Issue by hboetes** [dandavison/magit-delta#12]
I just changed the indenting of this line, displayed with `git diff`

![image](https://user-images.githubusercontent.com/2285225/91989971-70cec180-ed31-11ea-91ea-81363ac08d06.png)

As you can see the spaces I added are hilighted. When I display the same change in magit, those added spaces are not highlighted.

How can I configure magit-delta to use the same hilighting as in the console?

**Comment by hboetes** [comment]
Here is a side by side example, the first is from magit in Emacs, which has full 256 colour support BTW.
![image](https://user-images.githubusercontent.com/2285225/92281132-46306480-eefb-11ea-9b4e-c2cba73b6f07.png)
And the second is from terminator, whilst running git diff.
![image](https://user-images.githubusercontent.com/2285225/92281163-53e5ea00-eefb-11ea-884a-d6e2421f451f.png)

**Comment by dandavison** [comment]
Hi @hboetes, let's get to the bottom of this. Do you see _any_ within-line highlighting at all when using `magit-delta`? In general you should (like the word "Copy" in the [screenshot](https://user-images.githubusercontent.com/52205/80056404-23745500-84f2-11ea-9ecd-832376faf2f1.png) in the README). 

What is the value of the variable `xterm-color--support-truecolor` in your Emacs?

Here's something to try:

1. Capture some `delta` output with its ANSI escape sequences:
   ```
   git diff | delta > with-ansi-colors.txt
   ```

2. Open `with-ansi-colors.txt` in Emacs. You should see lots of raw ANSI escape sequences in the emacs buffer, like `^[[38;5;4m`

3. Do `M-x xterm-color-colorize-buffer`. That should suddenly make colors appear: i.e. it converts all the raw ANSI color escape codes into Emacs text properties. Does it look right? It should look the same as in your terminal.

**Comment by hboetes** [comment]
Hello Dan,

Thanks for your time:

xterm-color--support-truecolor is a variable defined in ‘xterm-color.el’.
Its value is t

Here is the result from git diff, which looks perfectly splendid:

[image: image.png]


This is the result of the file with-ansi-colors.txt in emacs with
xterm-color-colorize-buffer, which does something wrong.

[image: image.png]

Here is my init.el for reference:
https://raw.githubusercontent.com/hboetes/configs/master/.config/emacs/init.el
Which I also tried whilst commenting out:

(custom-theme-set-faces
 'zenburn
 '(font-lock-comment-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#DFAF8F")))))

And I also commented out using the zenburn theme completely, with the same
result.

% emacs --version
GNU Emacs 28.0.50

./configure --with-x --with-x-toolkit=gtk --without-makeinfo
--mandir=/usr/local/man

**Comment by dandavison** [comment]
> This is the result of the file with-ansi-colors.txt in emacs with
xterm-color-colorize-buffer, which does something wrong.

Hi @hboetes, the formatting in your reply got messed up unfortunately, so I can't see your screenshot.

Could you try `M-x xterm-color-test` please? Here's what I get:

![image](https://user-images.githubusercontent.com/52205/92766764-87de6680-f364-11ea-8584-d694af39d68c.png)

**Comment by hboetes** [comment]
Hello Dan, whilst running emacs as an X application it looks right, but
whilst running in terminator I get this:
![image](https://user-images.githubusercontent.com/2285225/92778195-399b8880-f3a1-11ea-8381-8bf6aa910178.png)

I tried the same in alacritty:
![image](https://user-images.githubusercontent.com/2285225/92778634-a44cc400-f3a1-11ea-81f0-3ee06e148cf1.png)

![image](https://user-images.githubusercontent.com/2285225/92778895-df4ef780-f3a1-11ea-9bf3-1e8a32eea8de.png)


Sooo.... Which terminal are you using? And do you have a config file for that terminal which you might want to share?

Mine are over here:
https://raw.githubusercontent.com/hboetes/configs/master/.config/alacritty/alacritty.yml
https://raw.githubusercontent.com/hboetes/configs/master/.config/terminator/config

**Comment by dandavison** [comment]
Hey @hboetes, the replies being sent by your mail client aren't getting formatted correctly in github! Would you be able to post them directly in the github web UI (or smartphone app)?

**Comment by hboetes** [comment]
Sorry about that, I've updated the comments, the image links work but are not rendered, no idea what causes that.

**Comment by dandavison** [comment]
OK, so that sounds like the problem is something to do with display of colors when emacs is running in a terminal emulator. Can you try running these color test scripts in your terminal emulator?

https://gitlab.com/gnachman/iterm2/-/raw/adhoc_3.3.20190827_203700/tests/24-bit-color.sh

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/92782916-5caf4380-f373-11ea-8340-fc0521c76650.png" alt="image" /></td></tr></table>

https://github.com/atomontage/xterm-color/tree/master/tests

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/92783035-75b7f480-f373-11ea-9e68-f0fbc1e227c2.png" alt="image" /></td></tr></table>

What is the value of the `COLORTERM` and `TERM` environment variables in your shell (`echo $TERM`) and as seen by emacs `(getenv "TERM")`?

**Comment by dandavison** [comment]
(I don't use Emacs a terminal application.)

**Comment by hboetes** [comment]
![image](https://user-images.githubusercontent.com/2285225/92805628-9145ee00-f3b9-11ea-8a9e-c8b9c5cc79ce.png)
![image](https://user-images.githubusercontent.com/2285225/92805968-d9fda700-f3b9-11ea-9b3e-474d2c4139d6.png)
```
% echo $TERM
xterm-256color
% echo $COLORTERM
truecolor
```

getenv TERM returns dumb
getenv COLORTERM returns [no match]

**Comment by dandavison** [comment]
Great, so it looks like there's no problem with your terminal.

OK, I'm seeing the same as you when I run emacs as a terminal application (`emacs -nw`): the `xterm-color-test` output does not look correct:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/92808893-1fa27b80-f38a-11ea-96bc-fe1211add22e.png" alt="image" /></td></tr></table>

 I'm not sure why this is, and I'm not 100% sure what our expectations should be. @atomontage (author of xterm-color) do you have time to advise here? In a terminal emulator that is displaying 256 and truecolor colors correctly, should the `xterm-color-test` results render correctly in an `emacs -nw`?

**Comment by hboetes** [comment]
Might this be of interest? https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html

**Comment by hboetes** [comment]
Well I'll be damned o_O, that did the trick!
![image](https://user-images.githubusercontent.com/2285225/92815466-8cd30280-f3c4-11ea-9e62-4af27f93e467.png)

![image](https://user-images.githubusercontent.com/2285225/92815669-c0ae2800-f3c4-11ea-8a36-7d692b6b6e75.png)

**Comment by dandavison** [comment]
Yeah! I just found the same.

![image](https://user-images.githubusercontent.com/52205/92815711-7f9d2000-f392-11ea-833b-875fc182389c.png)

OK, great. So I'll add a note to the README pointing to that emacs doc page for people who want to use magit-delta with emacs running in a terminal.

Thanks for exploring this avenue!

**Comment by hboetes** [comment]
Just to show off everything works now, emacs on OpenBSD in tmux with full color support for delta. Yay!
![image](https://user-images.githubusercontent.com/2285225/92938616-0d3d4600-f44d-11ea-944c-e2cd1f60d37c.png)
