### ISSUE TITLE
Minimalistic minor mode indicator

### ISSUE THREAD

**Issue by caribpa** [dandavison/magit-delta#17]
Hi,

I'm loving the minor mode so far. The only thing that's minorly annoying me is the fact that the mode's indicator is not a simple Δ symbol:
https://github.com/dandavison/magit-delta/blob/f77e205956f4e4996db5b52670c61396d43b7aae/magit-delta.el#L72

Would you consider/approve changing it?

**Comment by dandavison** [comment]
Absolutely! That makes perfect sense, especially as you've pointed out that the minor-mode is only active under magit major-mode, so the "Magit" indicator will already be present. Fixed in b8526f890415374822514e488341d2b706d6bc2f.
