### ISSUE TITLE
This is package is so nice!

### ISSUE THREAD

**Issue by mplanchard** [dandavison/magit-delta#20]
Hey there, just wanted to say thinks for this package (and delta!). It resolves one of my only complaints about magit, which is that the diffs don't have syntax highlighting.

I'll close this issue so you don't have to worry about it, but seriously this is so awesome.

**Comment by dandavison** [comment]
Thank you @mplanchard! A lot of the credit for magit-delta goes to @atomontage for https://github.com/atomontage/xterm-color, which does all the hard work of transforming the ANSI color terminal sequences from delta into emacs color data structures.

**Comment by mplanchard** [comment]
My thanks to both of you then! I really can't overstate the quality of life improvement from this package. I do a lot of code review from emacs, both my own code prior to opening a PR and others' code (I even use `github-review` to review PRs without hitting the browser). This package really really improves the process of viewing any diff at all in magit. 

Delta on the command line was the one thing I still missed when using magit, but no longer!

Thanks again, and have a great weekend!
