### ISSUE TITLE
Tweak colors

### ISSUE THREAD

**Issue by haplo** [dandavison/magit-delta#29]
First of all, thanks for this great package!

Everything works well, but colors are a bit too dark. Compare:

Regular Magit diff:
![image](https://github.com/dandavison/magit-delta/assets/71658/cddbbfe3-5a45-4ff8-9796-cfefd38767e4)

`magit-delta` diff:
![image](https://github.com/dandavison/magit-delta/assets/71658/37693364-17c1-43d9-8dca-5d571f4e817c)

This might be my theme (_solarized-dark_ from [doom-themes](https://github.com/hlissner/emacs-doom-themes)), but I would expect the colors to be brighter. Is it possible to tweak them? Any hints at where to look?

Thanks!

**Comment by dandavison** [comment]
Hi @haplo, glad you're getting value out of `magit-delta`. I've been using it daily for a few years now. The colors all come from delta itself, so you have the full range of delta options to choose from. You probably want to look at `--syntax-theme` (for setting the foreground colors) and then all the `--*-style` options (for setting background colors, etc). For docs, see `delta --help` and the delta manual, e.g.

https://dandavison.github.io/delta/choosing-colors-styles.html
https://dandavison.github.io/delta/custom-themes.html

and you could get some ideas by browsing PRs that add custom themes: https://github.com/dandavison/delta/pulls?q=is%3Apr+theme (they _should_ all have screenshots) and last but not least by looking at the contributed theme configs:

https://github.com/dandavison/delta/blob/main/themes.gitconfig

(closing this ticket but feel free to continue the discussion)

**Comment by haplo** [comment]
@dandavison Thanks a lot for the thorough reply! Now it makes sense that magit-delta transforms the ANSI color sequences for Emacs to use, so of course :man_facepalming: the colors must be set up in origin.

I believe this information would be useful to have in the README, if you agree I can submit a documentation PR.

**Comment by dandavison** [comment]
Please do make a documentation PR! The README is pretty minimal right now. FWIW my magit-delta config currently is

```emacs-lisp
(use-package magit-delta
  :after magit
  :config
  (add-hook 'magit-mode-hook (lambda () (magit-delta-mode +1)))
  (add-to-list 'magit-delta-delta-args "--no-gitconfig")
  (add-to-list 'magit-delta-delta-args "--light")
  (setq magit-delta-delta-executable "/opt/homebrew/bin/delta"))
```
